# Generated by Django 4.2.1 on 2023-06-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='Blog',
        ),
    ]
